from __future__ import annotations

import re
import unittest
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
PIN = (ROOT / ".github" / "aw" / "gh-aw-version.txt").read_text(encoding="utf-8").strip()
SOURCES = {
    "process-issue-triage": {
        "max-ai-credits: 50",
        "max-daily-ai-credits: 100",
        "timeout-minutes: 8",
        "max-turns: 8",
        "allowed-repos: public",
        "issues: read",
        "add-labels:",
        "add-comment:",
    },
    "weekly-process-backlog-review": {
        "max-ai-credits: 100",
        "max-daily-ai-credits: 100",
        "timeout-minutes: 10",
        "max-turns: 10",
        'allowed-repos: [lehard/dev-platform, "${{ github.repository }}"]',
        "issues: read",
        "workflow_call:",
        "create-issue:",
        "Review context (`reviewed_at`, exact `main` SHA, previous-review boundary)",
        "Root-cause candidates",
        "Likely resolved/superseded",
        "Подтверждённый дефект",
        "наблюдать",
    },
    "architecture-health-review": {
        "max-ai-credits: 100",
        "max-daily-ai-credits: 100",
        "timeout-minutes: 10",
        "max-turns: 10",
        'allowed-repos: [lehard/dev-platform, "${{ github.repository }}"]',
        "toolsets: [issues, pull_requests, repos]",
        "workflow_call:",
        "create-issue:",
        "dev-platform/capabilities/architecture-health-review.md",
        "openspec/specs/architecture-health/spec.md",
        "Never propose or make a code edit",
        "never create or recommend creating a managed task",
        "relevant private\nBacklog issues and recent merged changes",
    },
}
AGENT_JOB_TIMEOUT_MINUTES = 30
GH_AW_ACTION_REF = "69763a0390c8438e006d545f1faef1fab742719d"
AGENTIC_STEP_TIMEOUT_MINUTES = {
    "process-issue-triage": 8,
    "weekly-process-backlog-review": 10,
    "architecture-health-review": 10,
}

class AgenticWorkflowTests(unittest.TestCase):
    def test_pin_is_exact_stable_semver(self) -> None:
        self.assertRegex(PIN, r"^v\d+\.\d+\.\d+$")

    def test_gateway_security_fix_is_immutable_and_public_only(self) -> None:
        config = (ROOT / ".github" / "workflows" / "aw.json").read_text(encoding="utf-8")
        self.assertIn('"ghcr.io/github/gh-aw-mcpg:v0.4.8"', config)
        self.assertIn('"image": "ghcr.io/github/gh-aw-mcpg:v0.4.9"', config)
        self.assertRegex(config, r'"digest": "sha256:[0-9a-f]{64}"')

    def test_sources_are_bounded_codex_read_only(self) -> None:
        forbidden = ("create-pull-request:", "push-to-pull-request-branch:", "close-issue:", "merge-pull-request:")
        for name, required in SOURCES.items():
            text = (ROOT / ".github" / "workflows" / f"{name}.md").read_text(encoding="utf-8")
            self.assertIn("engine: codex", text)
            self.assertIn("contents: read", text)
            if name == "process-issue-triage":
                self.assertIn("workflow_dispatch:", text)
            else:
                self.assertNotIn("workflow_dispatch:", text)
            self.assertIn("threat-detection:", text)
            self.assertIn("bash: [\"*\"]", text)
            self.assertIn("jobs:\n  agent:\n    timeout-minutes: 30", text)
            self.assertNotIn("private-to-public-flows:", text)
            self.assertNotIn("MCP_GATEWAY_ALLOWED_MOUNT_ROOTS:", text)
            for value in required:
                self.assertIn(value, text)
            for value in forbidden:
                self.assertNotIn(value, text)

    def test_compiled_agent_jobs_have_bounded_whole_job_deadlines(self) -> None:
        for name in SOURCES:
            with self.subTest(name=name):
                lock = ROOT / ".github" / "workflows" / f"{name}.lock.yml"
                lock_doc = yaml.safe_load(lock.read_text(encoding="utf-8"))
                timeout = lock_doc["jobs"]["agent"].get("timeout-minutes")
                self.assertIsInstance(timeout, int)
                self.assertGreater(timeout, AGENTIC_STEP_TIMEOUT_MINUTES[name])
                self.assertLess(timeout, 360)
                self.assertEqual(timeout, AGENT_JOB_TIMEOUT_MINUTES)

    def test_compiled_locks_are_pinned_and_match_source_version(self) -> None:
        for name in SOURCES:
            text = (ROOT / ".github" / "workflows" / f"{name}.lock.yml").read_text(encoding="utf-8")
            self.assertIn(f'"compiler_version":"{PIN}"', text)
            self.assertIn(f"generated by gh-aw ({PIN})", text)
            self.assertRegex(text, r"ghcr\.io/github/gh-aw-mcpg:v0\.4\.18@sha256:[0-9a-f]{64}")
            self.assertIn(f"github/gh-aw/actions/setup@{GH_AW_ACTION_REF}", text)
            agent = text[text.index("  agent:") : text.index("  conclusion:")]
            if name == "process-issue-triage":
                self.assertIn('"repos": "public"', agent)
            else:
                self.assertIn("GITHUB_MCP_SERVER_TOKEN: ${{ steps.private_read_token.outputs.token }}", agent)
            self.assertRegex(agent, r"ghcr\.io/github/gh-aw-mcpg:v0\.4\.18@sha256:[0-9a-f]{64}")
            self.assertNotIn("gh-aw-mcpg:v0.4.8", agent)
            self.assertNotIn("GH_AW_MCP_GATEWAY_CUSTOM_ENV_NAMES", agent)
            self.assertIn('export MCP_GATEWAY_ALLOWED_MOUNT_ROOTS="${GITHUB_WORKSPACE}:rw,', agent)
            for uses in re.findall(r"^\s*uses:\s+[^@\s]+@([^\s#]+)", text, flags=re.MULTILINE):
                self.assertRegex(uses, r"^[0-9a-f]{40}$", msg=f"non-immutable action reference: {uses}")

    def test_triage_only_names_available_read_tools(self) -> None:
        text = (ROOT / ".github" / "workflows" / "process-issue-triage.md").read_text(encoding="utf-8")
        for tool in ("`issue_read`", "`list_label`", "`search_issues`"):
            self.assertIn(tool, text)
        self.assertIn("Do not use `search_repositories`", text)

    def test_triage_safe_output_cli_is_the_only_shell_exception(self) -> None:
        text = (ROOT / ".github" / "workflows" / "process-issue-triage.md").read_text(encoding="utf-8")
        self.assertIn("`safeoutputs`\nCLI is the sole shell exception", text)
        self.assertIn("direct schema-derived\n`safeoutputs` command", text)
        self.assertIn("do not wrap it in `bash`, `sh`, or a login shell", text)
        self.assertIn("Do not report that a comment was posted unless that command confirms", text)

    def test_weekly_review_requires_freshness_and_preserves_source_issue_read_only_boundary(self) -> None:
        text = (ROOT / ".github" / "workflows" / "weekly-process-backlog-review.md").read_text(encoding="utf-8")
        for value in ("exact current commit SHA", "previous-review boundary", "root cause", "inspect current default-branch"):
            with self.subTest(value=value):
                self.assertIn(value, text)
        self.assertIn("Classification: context-gap", text)
        self.assertIn("Likely context destination", text)
        self.assertIn("ordinary process-friction", text)
        self.assertIn("## Краткие findings", text)
        self.assertIn("or close/relabel/comment on source evidence", text)
        self.assertIn("Подтверждённый дефект", text)
        self.assertIn("use `наблюдать`", text)

    def test_architecture_review_separates_lens_from_classified_finding_fields(self) -> None:
        capability = (ROOT / "dev-platform" / "capabilities" / "architecture-health-review.md").read_text(encoding="utf-8")
        for value in ("evidence lens", "Подтверждённый дефект", "высокая | средняя | низкая", "новый | сохраняется | уже в работе | вероятно устранён | наблюдать"):
            with self.subTest(value=value):
                self.assertIn(value, capability)

    def test_public_repository_has_no_combined_platform_health_trigger(self) -> None:
        # The combined private review is owned by the private caller repository.
        self.assertFalse((ROOT / ".github" / "workflows" / "platform-health-review.yml").exists())

    def test_private_review_read_token_and_report_boundary(self) -> None:
        process = (ROOT / ".github" / "workflows" / "weekly-process-backlog-review.md").read_text(encoding="utf-8")
        architecture = (ROOT / ".github" / "workflows" / "architecture-health-review.md").read_text(encoding="utf-8")
        for source in (process, architecture):
            self.assertIn("inlined-imports: true", source)
            self.assertIn("github-token: ${{ steps.private_read_token.outputs.token }}", source)
            self.assertIn("permission-contents: read", source)
            self.assertNotIn("permission-issues: write", source)
            self.assertNotIn("private-to-public-flows:", source)
        self.assertIn("permission-issues: read", process)
        self.assertIn("permission-pull-requests: read", process)
        self.assertIn("permission-issues: read", architecture)
        self.assertIn("permission-pull-requests: read", architecture)
        self.assertIn("## Краткие findings", architecture)
        self.assertIn('allowed-repos: [lehard/dev-platform, "${{ github.repository }}"]', process)
        self.assertIn("${{ github.event.repository.name }}", architecture)
        self.assertIn('allowed-repos: [lehard/dev-platform, "${{ github.repository }}"]', architecture)

    def test_reusable_review_locks_are_self_contained_in_private_caller(self) -> None:
        for name in ("weekly-process-backlog-review", "architecture-health-review"):
            lock = (ROOT / ".github" / "workflows" / f"{name}.lock.yml").read_text(encoding="utf-8")
            self.assertNotIn("{{#runtime-import", lock)



if __name__ == "__main__":
    unittest.main()
