"""The release manifest of platform-owned file digests must match the template tree.

`template/dev-platform/platform-manifest.json` is generated by
`scripts/generate_platform_manifest.py`. A stale manifest (a template file changed
without regenerating it) fails platform validation here, naming the path.
"""
from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import subprocess
import sys
import tomllib
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = ROOT / "scripts" / "generate_platform_manifest.py"
MANIFEST = ROOT / "template" / "dev-platform" / "platform-manifest.json"
SURFACE = ROOT / "template" / "dev-platform" / "protected-surface.toml"
EVIDENCE_GATE_SCRIPTS = (
    "scripts/agent_friction.py",
    "scripts/requirement_retrospective.py",
    "scripts/requirement_intake.py",
    "scripts/execute_managed_task.py",
    "scripts/orchestrate_pre_authoring.py",
)


def load_generator():
    spec = importlib.util.spec_from_file_location("generate_platform_manifest_under_test", GENERATOR)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class PlatformManifestTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.generator = load_generator()
        cls.expected = cls.generator.build_manifest()
        cls.committed_text = MANIFEST.read_text(encoding="utf-8")

    def test_committed_manifest_equals_the_generated_one(self) -> None:
        problems = self.generator.mismatches(self.expected, self.committed_text)
        self.assertEqual([], problems, "stale platform manifest; run python3 scripts/generate_platform_manifest.py --write\n" + "\n".join(problems))

    def test_check_entrypoint_passes_on_the_committed_tree(self) -> None:
        completed = subprocess.run([sys.executable, str(GENERATOR), "--check"], cwd=ROOT, text=True, capture_output=True)
        self.assertEqual(0, completed.returncode, completed.stdout + completed.stderr)

    def test_stale_digest_fails_naming_the_mismatching_path(self) -> None:
        committed = json.loads(self.committed_text)
        committed["files"]["scripts/platform_divergence.py"] = "0" * 64
        problems = self.generator.mismatches(self.expected, json.dumps(committed))
        self.assertEqual(1, len(problems), problems)
        self.assertIn("scripts/platform_divergence.py", problems[0])

    def test_template_file_added_or_removed_without_regenerating_is_named(self) -> None:
        committed = copy.deepcopy(json.loads(self.committed_text))
        committed["files"]["scripts/brand_new.py"] = "1" * 64
        del committed["files"]["scripts/dev.py"]
        problems = "\n".join(self.generator.mismatches(self.expected, json.dumps(committed)))
        self.assertIn("scripts/brand_new.py: listed in the committed manifest but not a platform-owned template file", problems)
        self.assertIn("scripts/dev.py: missing from the committed manifest", problems)

    def test_every_digest_is_the_sha256_of_the_template_bytes(self) -> None:
        manifest = json.loads(self.committed_text)
        self.assertEqual(1, manifest["version"])
        self.assertTrue(manifest["files"])
        for relative, digest in manifest["files"].items():
            with self.subTest(relative=relative):
                self.assertEqual(hashlib.sha256((ROOT / "template" / relative).read_bytes()).hexdigest(), digest)

    def test_manifest_lists_neither_itself_nor_project_owned_nor_templated_files(self) -> None:
        files = json.loads(self.committed_text)["files"]
        self.assertNotIn("dev-platform/platform-manifest.json", files)
        for owned in ("dev-platform/local-hotfixes.toml", "dev-platform/checks.toml", "docs/engineering/project-rules.md"):
            self.assertNotIn(owned, files)
        self.assertFalse([path for path in files if path.endswith(".jinja")])
        self.assertIn("dev-platform/protected-surface.toml", files)
        self.assertIn("scripts/platform_divergence.py", files)

    def test_manifest_carries_no_platform_version(self) -> None:
        self.assertEqual({"version", "files", "project_harness_owned"}, set(json.loads(self.committed_text)))

    def test_detector_and_manifest_are_protected_not_hotfixable(self) -> None:
        surface = tomllib.loads(SURFACE.read_text(encoding="utf-8"))
        protected = [self.generator.glob_regex(entry["path"]) for entry in surface["protected"]]
        for path in ("scripts/platform_divergence.py", "dev-platform/platform-manifest.json"):
            with self.subTest(path=path):
                self.assertTrue(any(regex.match(path) for regex in protected))
                self.assertNotIn(path, surface["hotfixable"])

    def test_evidence_gate_scripts_are_protected_not_hotfixable(self) -> None:
        surface = tomllib.loads(SURFACE.read_text(encoding="utf-8"))
        protected = {
            entry["path"]: entry["category"] for entry in surface["protected"]
        }
        for path in EVIDENCE_GATE_SCRIPTS:
            with self.subTest(path=path):
                self.assertEqual("routing-provenance-evidence", protected.get(path))
                self.assertNotIn(path, surface["hotfixable"])


if __name__ == "__main__":
    unittest.main()
