from __future__ import annotations

import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PIN = (ROOT / ".github" / "aw" / "gh-aw-version.txt").read_text(encoding="utf-8").strip()
SAFE_OUTPUTS_MOUNT_ROOTS = (
    "${GITHUB_WORKSPACE}:rw,${RUNNER_TEMP}/gh-aw/safeoutputs:rw,/tmp/gh-aw:rw"
)
SOURCES = {
    "process-issue-triage": {
        "max-ai-credits: 50",
        "max-daily-ai-credits: 100",
        "timeout-minutes: 8",
        "max-turns: 8",
        "allowed-repos: public",
        "add-labels:",
        "add-comment:",
    },
    "weekly-process-backlog-review": {
        "max-ai-credits: 100",
        "max-daily-ai-credits: 100",
        "timeout-minutes: 10",
        "max-turns: 10",
        "allowed-repos: public",
        "schedule: weekly",
        "workflow_dispatch:",
        "create-issue:",
    },
}


class AgenticWorkflowTests(unittest.TestCase):
    def test_pin_is_exact_stable_semver(self) -> None:
        self.assertRegex(PIN, r"^v\d+\.\d+\.\d+$")

    def test_gateway_security_fix_is_immutable_and_public_only(self) -> None:
        config = (ROOT / ".github" / "workflows" / "aw.json").read_text(encoding="utf-8")
        self.assertIn('"ghcr.io/github/gh-aw-mcpg:v0.4.8"', config)
        self.assertIn('"image": "ghcr.io/github/gh-aw-mcpg:v0.4.9"', config)
        self.assertRegex(config, r'"digest": "sha256:[0-9a-f]{64}"')

    def test_sources_are_bounded_codex_read_only(self) -> None:
        forbidden = ("create-pull-request:", "push-to-pull-request-branch:", "close-issue:", "merge-pull-request:")
        for name, required in SOURCES.items():
            text = (ROOT / ".github" / "workflows" / f"{name}.md").read_text(encoding="utf-8")
            self.assertIn("engine: codex", text)
            self.assertIn("contents: read", text)
            self.assertIn("issues: read", text)
            self.assertIn("workflow_dispatch:", text)
            self.assertIn("threat-detection:", text)
            self.assertNotIn("private-to-public-flows:", text)
            self.assertIn(f'MCP_GATEWAY_ALLOWED_MOUNT_ROOTS: "{SAFE_OUTPUTS_MOUNT_ROOTS}"', text)
            for value in required:
                self.assertIn(value, text)
            for value in forbidden:
                self.assertNotIn(value, text)

    def test_compiled_locks_are_pinned_and_match_source_version(self) -> None:
        for name in SOURCES:
            text = (ROOT / ".github" / "workflows" / f"{name}.lock.yml").read_text(encoding="utf-8")
            self.assertIn(f'"compiler_version":"{PIN}"', text)
            self.assertIn(f"generated by gh-aw ({PIN})", text)
            self.assertIn("ghcr.io/github/gh-aw-mcpg:v0.4.9@sha256:", text)
            agent = text[text.index("  agent:") : text.index("  conclusion:")]
            self.assertIn('"repos": "public"', agent)
            self.assertIn("ghcr.io/github/gh-aw-mcpg:v0.4.9@sha256:", agent)
            self.assertNotIn("gh-aw-mcpg:v0.4.8", agent)
            self.assertIn(f"export MCP_GATEWAY_ALLOWED_MOUNT_ROOTS={SAFE_OUTPUTS_MOUNT_ROOTS}", agent)
            for uses in re.findall(r"^\s*uses:\s+[^@\s]+@([^\s#]+)", text, flags=re.MULTILINE):
                self.assertRegex(uses, r"^[0-9a-f]{40}$", msg=f"non-immutable action reference: {uses}")

    def test_triage_only_names_available_read_tools(self) -> None:
        text = (ROOT / ".github" / "workflows" / "process-issue-triage.md").read_text(encoding="utf-8")
        for tool in ("`issue_read`", "`list_label`", "`search_issues`"):
            self.assertIn(tool, text)
        self.assertIn("Do not use `search_repositories`", text)


if __name__ == "__main__":
    unittest.main()
