from __future__ import annotations

import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PIN = (ROOT / ".github" / "aw" / "gh-aw-version.txt").read_text(encoding="utf-8").strip()
SOURCES = {
    "process-issue-triage": {
        "max-ai-credits: 50",
        "max-daily-ai-credits: 100",
        "timeout-minutes: 8",
        "max-turns: 8",
        "add-labels:",
        "add-comment:",
    },
    "weekly-process-backlog-review": {
        "max-ai-credits: 100",
        "max-daily-ai-credits: 100",
        "timeout-minutes: 10",
        "max-turns: 10",
        "schedule: weekly",
        "workflow_dispatch:",
        "create-issue:",
    },
}


class AgenticWorkflowTests(unittest.TestCase):
    def test_pin_is_exact_stable_semver(self) -> None:
        self.assertRegex(PIN, r"^v\d+\.\d+\.\d+$")

    def test_sources_are_bounded_codex_read_only(self) -> None:
        forbidden = ("create-pull-request:", "push-to-pull-request-branch:", "close-issue:", "merge-pull-request:")
        for name, required in SOURCES.items():
            text = (ROOT / ".github" / "workflows" / f"{name}.md").read_text(encoding="utf-8")
            self.assertIn("engine: codex", text)
            self.assertIn("contents: read", text)
            self.assertIn("issues: read", text)
            self.assertIn("workflow_dispatch:", text)
            self.assertIn("threat-detection:", text)
            for value in required:
                self.assertIn(value, text)
            for value in forbidden:
                self.assertNotIn(value, text)

    def test_compiled_locks_are_pinned_and_match_source_version(self) -> None:
        for name in SOURCES:
            text = (ROOT / ".github" / "workflows" / f"{name}.lock.yml").read_text(encoding="utf-8")
            self.assertIn(f'"compiler_version":"{PIN}"', text)
            self.assertIn(f"generated by gh-aw ({PIN})", text)
            for uses in re.findall(r"^\s*uses:\s+[^@\s]+@([^\s#]+)", text, flags=re.MULTILINE):
                self.assertRegex(uses, r"^[0-9a-f]{40}$", msg=f"non-immutable action reference: {uses}")


if __name__ == "__main__":
    unittest.main()
